### ISSUE TITLE
Argument mismatch between bosh cpi and softlayer CPI for VM deletion

### ISSUE THREAD

**Issue by ScarletTanager** [cloudfoundry/bosh-softlayer-cpi#108]
When trying to do a simple deployment to SL, we are getting the following:

    D, [2016-04-07 21:54:51 #32412] [] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"delete_vm","arguments":["17309677"],"context":{"director_uuid":"d4f53e59-f1ea-4290-9789-4cd5a1d4c7d5"}} with command: /var/vcap/jobs/cpi/bin/cpi
    D, [2016-04-07 21:54:51 #32412] [] DEBUG -- DirectorJobRunner: External CPI got response: {"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"Extracting method arguments from payload: Not enough arguments, expected 2, got 1","ok_to_retry":false},"log":""}, err: , exit_status: pid 32429 exit 0

In looking at the code on each side of the junction, it appears that bosh expects to provide only the VM cid [see here](https://github.com/cloudfoundry/bosh/blob/93a2522b3a6a58cc3d24f6ea10a9dba0a9a421bb/bosh-director/lib/bosh/director/vm_deleter.rb#L18-L21).

It looks as if the SL CPI, however, is expecting two arguments, both the VM cid and an agent id, and this is causing our deployment to fail.

@ScarletTanager & @swetharepakula, RuntimeOG team

**Comment by jianqiu** [comment]
@ScarletTanager  Thanks for your trial !
Due to the specific requirement of SoftLayer infrastructure, bosh-softlayer-cpi-release-v1 could not work with the bosh version from community. As we implemented os_reload function in bosh-softlayer-cpi, there needs to be some changes to bosh release, just like  you mentioned, delete_vm of bosh.  Please try the offerings as follows:
https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release/releases

We are looking forward  your comments, thanks!

**Comment by ScarletTanager** [comment]
@jianqiu - thanks for the response.  I have a couple of comments:
 
1. I'm decidedly not a fan of the nested tarball approach to packaging - there is no way to see what's really in the release tarball, since you just get more tarballs.  Not only that, but I think you have golang included twice in your release, since I get this (partial output) from `tar tzf bosh_softlayer_cpi.tgz` in the extracted `packages` directory:

    ./golang_1.5.3/
    ./golang_1.5.3/go1.5.3.linux-amd64.tar.gz

but there is also a golang tarball already present in `packages`...

2. in your `packaging` script, I don't see how the variables `BOSH_PACKAGES_DIR` and `BOSH_INSTALL_TARGET` are initialized.  I can try to work around that, but I I think some work/documentation is needed to make this production-ready.

@ScarletTanager

**Comment by ScarletTanager** [comment]
@jianqiu - still getting an error, albeit a different one:

    D, [2016-04-08 15:23:04 #3532] [] DEBUG -- DirectorJobRunner: External CPI sending request: {"method":"delete_vm","arguments":["17309677"],"context":{"director_uuid":"d4f53e59-f1ea-4290-9789-4cd5a1d4c7d5"}} with command: /var/vcap/jobs/cpi/bin/cpi
    D, [2016-04-08 15:23:04 #3532] [] DEBUG -- DirectorJobRunner: External CPI got response: , err: , exit_status: pid 3549 exit 1
    E, [2016-04-08 15:23:04 #3532] [] ERROR -- DirectorJobRunner: Worker thread raised exception: Invalid CPI response - SchemaValidationError: Expected instance of Hash, given instance of NilClass - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_cpi-1.3215.3.0/lib/cloud/external_cpi.rb:141:in `rescue in validate_response'

Thanks,

@ScarletTanager

**Comment by jianqiu** [comment]
@ScarletTanager 
Could you please look into the bosh-softlayer-cpi-release project, we had already made some documents there on how to use bosh-init to deploy bosh director with softlayer-ecpi.
https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release/releases

**Comment by jianqiu** [comment]
For bosh-softlayer-cpi-release-v1, you need to use customized bosh release (not the version of community), bosh-softlayer-stemcell, our bosh-init.
you can download them from v1.49.0 release notes.

**Comment by ScarletTanager** [comment]
@jianqiu - I am using the community directory with your 2.1.0, about which you state, "from this release, you can use the BOSH release from community."  Is that not actually the case?

**Comment by jianqiu** [comment]
@ScarletTanager  That is fine, could you please show me your manifest yaml for bosh director? And how did you use the cpi release? Thanks!

**Comment by ScarletTanager** [comment]
@jianqiu - before we deploy the 2.1 CPI, we need to know whether or not we can expect the delete_vm operation to work - is it still broken in the 2.1 CPI, or should we expect full functionality to be available?

**Comment by ScarletTanager** [comment]
@jianqiu - we are getting this error on bosh-init deploy with the 2.1 CPI and your 2.2 candidate bosh release:

```
Command 'deploy' failed:
  Installing CPI:
    Rendering and uploading Jobs:
      Rendering job templates for installation:
        Rendering templates for job 'softlayer_cpi/71a8bf55509afc4ba579169135d0ca2baf21f690':
          Rendering template src: cpi.json.erb, dst: config/cpi.json:
            Rendering template src: /root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/bosh-init-release923838271/extracted_jobs/softlayer_cpi/templates/cpi.json.erb, dst: /root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/rendered-jobs502132488/config/cpi.json:
              Running ruby to render templates:
                Running command: 'ruby /root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/erb-renderer174056314/erb-render.rb /root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/erb-renderer174056314/erb-context.json /root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/bosh-init-release923838271/extracted_jobs/softlayer_cpi/templates/cpi.json.erb /root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/rendered-jobs502132488/config/cpi.json', stdout: '', stderr: '/root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/erb-renderer174056314/erb-render.rb:180:in `rescue in render': Error filling in template '/root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/bosh-init-release923838271/extracted_jobs/softlayer_cpi/templates/cpi.json.erb' for softlayer_cpi/0 (line 40: #<TemplateEvaluationContext::UnknownProperty: Can't find property 'agent.blobstore.address', or 'blobstore.address'>) (RuntimeError)
	from /root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/erb-renderer174056314/erb-render.rb:166:in `render'
	from /root/.bosh_init/installations/0216f9be-251a-41c7-5c50-407eb315b090/tmp/erb-renderer174056314/erb-render.rb:191:in `<main>'
':
```

I have attached our manifest (user/pws scrubbed) here:

[rtog-sl-bosh-init.yml.txt](https://github.com/cloudfoundry/bosh-softlayer-cpi/files/226100/rtog-sl-bosh-init.yml.txt)

I do see a blobstore.address property in at least one location in our manifest, but I'm not sure in what context that error message is being generated, so I am unsure how to fix.  Can you please take a look?

Thanks,

@ScarletTanager & @jberkhahn, CF RuntimeOG team

**Comment by jianqiu** [comment]
@ScarletTanager 
Sorry of the misunderstanding for the deploy using bosh-softlayer-cpi-v2.
The main problem is that you are using the wrong manifest yaml, please take this as reference:
https://github.com/cloudfoundry-incubator/bosh-softlayer-cpi-release/blob/develop_v2/docs/bosh-init-usage.md
And I just corrected the manifest for you, please try it again
[rtog-sl-bosh-init-V2.yml.txt](https://github.com/cloudfoundry/bosh-softlayer-cpi/files/227108/rtog-sl-bosh-init-V2.yml.txt)

**Comment by jianqiu** [comment]
@ScarletTanager @jberkhahn
We will update our readme in future.  Sorry for the confusion caused to you.

**Comment by maximilien** [comment]
I am closing this issue as being resolved. If others feel differently, please reopen with reasoning.
